version: '3.9'

services:

  backend:
    build: .
    restart: always
    ports:
      - 9000:9000
    environment:
      PORT: 9000
    volumes:
      - ./:/home/app

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/home/app

