# Step-1: Build production bundle from source code
FROM node:21-alpine as builder

WORKDIR /home/app

COPY package.json .
RUN npm install

COPY . .
RUN npm run build

# Step-2: Serve Production build
FROM node:21-alpine

WORKDIR /home/app

COPY --from=builder /home/app/package.json .
COPY --from=builder /home/app/dist ./dist

RUN npm install --only=production
ENV NODE_ENV=production

CMD [ "npm", "start" ]